refactor: add event handler to tab-item slot
kelvininc/ui-components pull request #104
Opened 2022-07-12 16:06 UTC by GoncaloCamaz

2022-07-12 16:07 UTC, djcouto approved these changes

2022-07-12 16:23 UTC, ricardogoncalves89 requested changes

2022-07-12 16:23 UTC, ricardogoncalves89 commented on packages/ui-components/src/components/tab-list/tab-list.tsx
> +	private handleSlotChange = () => {
you shouldn't replicate the code please call the `handleSlotChange` inside the `componentDidRender`.

2022-07-15 14:44 UTC, miguelpinto98 approved these changes

2022-07-15 16:04 UTC, ricardogoncalves89 approved these changes

2022-07-18 11:07 UTC, merged