feat(badge-button): add `kv-badge` component
kelvininc/ui-components pull request #114
Opened 2022-07-28 18:06 UTC by djcouto

2022-07-29 08:59 UTC, ricardogoncalves89 commented
@djcouto Please add some screenshots to the description.

2022-07-29 14:03 UTC, ricardogoncalves89 commented
@djcouto this badge should have a state? and should be used inside the `kv-tree-item` maybe. Please evaluate this possibility

2022-08-01 11:46 UTC, miguelpinto98 approved these changes
👍

2022-08-01 11:47 UTC, miguelpinto98 requested changes
Export the component in angular library

2022-08-01 13:54 UTC, miguelpinto98 approved these changes
🚀

2022-08-01 14:12 UTC, pedrorebelocosta approved these changes

2022-08-02 17:46 UTC, ricardogoncalves89 approved these changes

2022-08-03 11:33 UTC, djcouto commented on packages/ui-components/src/components/tree-item/readme.md
> +# _<kv-tree-item>_
it's a local linter config, I'll reset this.

2022-08-04 09:46 UTC, merged