feat(dropdown-group): add options groups to dropdown single and multi select
kelvininc/ui-components pull request #120
Opened 2022-08-10 09:56 UTC by djcouto

Now dropdown options can be grouped by a name.

**Screenshots**
<img width="800" alt="Screenshot 2022-08-10 at 10 43 43" src="https://user-images.githubusercontent.com/17494742/183872652-523a6e92-5e86-4219-9a36-c291c22391e8.png">
<img width="800" alt="Screenshot 2022-08-10 at 10 43 38" src="https://user-images.githubusercontent.com/17494742/183872667-9119bdf4-65ff-4f6b-b931-394c54e3321b.png">

2022-08-10 12:53 UTC, pedrorebelocosta commented on packages/ui-components/src/components/dropdown-group/dropdown-group.scss
> +		&:not(not-last-child) {
remove this

2022-08-10 12:55 UTC, pedrorebelocosta commented on packages/ui-components/src/components/dropdown-group/readme.md
> +# _<kv-dropdown-group>_
suggestion: `*<kv-dropdown-group>*`

2022-08-10 12:56 UTC, pedrorebelocosta commented on packages/ui-components/src/components/dropdown-group/readme.md
> +<kv-single-select-dropdown label="Default Timezone"> </kv-single-select-dropdown>
update with the correct component tag

2022-08-10 12:57 UTC, pedrorebelocosta commented on packages/ui-components/src/components/dropdown-list-item/dropdown-list-item.scss
> +
-

2022-08-10 13:00 UTC, pedrorebelocosta requested changes
just minor changes, other than that lgtm :D good improvement

2022-08-10 13:04 UTC, TheSnakeRekt approved these changes
LGTM

2022-08-10 15:07 UTC, pedrorebelocosta approved these changes

2022-08-11 10:37 UTC, ricardogoncalves89 approved these changes
LGTM ;)

2022-08-11 10:37 UTC, ricardogoncalves89 commented on packages/ui-components/src/components/multi-select-dropdown/multi-select-dropdown.types.ts
> +	/** (optional) The object with indexed by the dropdown labes and its selected value */
typo `labels`

2022-08-11 18:42 UTC, miguelpinto98 requested changes
Almost ok! Only 3 questions before the approve.

2022-08-11 18:42 UTC, miguelpinto98 commented on packages/ui-components/src/components/multi-select-dropdown/multi-select-dropdown.tsx
> +		this.selectedOptions[option] = !!!this.selectedOptions[option];
👍

2022-08-11 18:42 UTC, miguelpinto98 commented on packages/ui-components/src/components/multi-select-dropdown/multi-select-dropdown.tsx
> +	private getSelectedOptionsCount = (): string[] => {
this can be moved to an util?

2022-08-11 18:42 UTC, miguelpinto98 commented on packages/ui-components/src/components/multi-select-dropdown/multi-select-dropdown.tsx
> +			this._selectionDisplayValue = this.getSelectedOptionsCount().reduce((acc, optionKey, currentIndex, selectedOptionsArray) => {
can we move this to an util?

2022-08-12 08:47 UTC, djcouto commented on packages/ui-components/src/components/multi-select-dropdown/multi-select-dropdown.tsx
> +	private getSelectedOptionsCount = (): string[] => {
Yes it can and it will 👍

2022-08-12 10:38 UTC, miguelpinto98 approved these changes
🚀 
EDIT: I didn't saw that is already banged. 😀

2022-08-12 10:38 UTC, miguelpinto98 commented on packages/ui-components/src/components/multi-select-dropdown/multi-select-dropdown.tsx
> +	@Prop({ reflect: true }) selectedOptions?: { [key: string]: boolean } = {};
this is kind a breaking change. Probably is better to bang the commit message.

2022-08-12 12:15 UTC, danielcarvalhopt approved these changes

2022-08-12 12:53 UTC, merged