feat(select-option): add bottom slot for content
kelvininc/ui-components pull request #129
Opened 2022-08-15 21:26 UTC by pedrorebelocosta

2022-08-15 21:43 UTC, miguelpinto98 requested changes
Seems good, only two things to think about.

2022-08-15 21:43 UTC, miguelpinto98 commented on packages/ui-components/src/components/select-option/select-option.scss
> +		height: fit-content;
this can be removed I guess. If we want to fit all the content we can set the `--select-item-height` to `unset`

2022-08-15 21:43 UTC, miguelpinto98 commented on packages/ui-components/src/components/select-option/select-option.scss
> +		align-items: flex-start;
probably is better to define this is a variable too

2022-08-16 10:34 UTC, djcouto approved these changes
Well done 💪

2022-08-16 10:34 UTC, djcouto commented on packages/react-ui-components/src/stories/Components/SelectOption.stories.tsx
> +	children: <div>Hello</div>
👍

2022-08-16 10:34 UTC, djcouto commented on packages/ui-components/src/components/select-option/select-option.scss
> +			color: var(--select-item-label-color-selected);
👍

2022-08-16 10:34 UTC, djcouto commented on packages/ui-components/src/components/select/select.scss
>  	--select-border-color: #{kv-color('neutral-6')};
Nice ideia 👍 

Just a thought two avoid two CSS custom properties for the "same" property:
```suggestion
	--select-border: 1px solid #{kv-color('neutral-6')};
	--select-border-radius: #{$spacing};
```

2022-08-16 10:34 UTC, Insatisfeito approved these changes

2022-08-16 11:23 UTC, miguelpinto98 approved these changes
👍

2022-08-16 11:44 UTC, merged

2022-08-16 16:00 UTC, ricardogoncalves89 reviewed
Please take a look at the comments