fix(action button): remove focus height & width 100%
kelvininc/ui-components pull request #134
Opened 2022-08-19 14:24 UTC by laraujo7

2022-08-19 16:50 UTC, GoncaloCamaz approved these changes

2022-08-19 19:28 UTC, nelsonmestevao approved these changes

2022-08-22 09:13 UTC, djcouto approved these changes

2022-08-22 09:20 UTC, miguelpinto98 requested changes
This is a bypass solution. We should try to fix this behaviour correctly.

2022-08-22 10:44 UTC, laraujo7 commented
> This is a bypass solution. We should try to fix this behaviour correctly.

What I think it's happening is that the button doesn't have the props 'height: 100%' and 'width: 100%', but in the focus mode it has, so the button, when it gets focused, is trying to expand. That's why I think the solution is removing this props.

2022-08-22 11:20 UTC, miguelpinto98 commented
Try to add position absolute to the content, z-index: -1, left: 0. The before content will be the button content, and we see the blur effect working.
Right now, it's only a pixel, that push the button to down.

2022-08-22 12:24 UTC, laraujo7 commented
I added your suggestion for the focus problem. The only problem was that the left prop couldn't be 0, but it had to be the same as the padding 💪

2022-08-22 16:54 UTC, miguelpinto98 approved these changes
let's go!

2022-08-22 16:54 UTC, miguelpinto98 commented on packages/ui-components/src/components/action-button/action-button.scss
> +			inset: 0;
👍

2022-08-22 17:00 UTC, merged