feat(kv-link): add kv-link component
kelvininc/ui-components pull request #14
Opened 2022-02-17 15:22 UTC by pedrorebelocosta

2022-02-21 16:02 UTC, pedrorebelocosta commented on packages/ui-components/src/components/kv-link/kv-link.tsx
> +					<div class="label" onClick={this.onLabelClick}>{this.label}</div>
@ricardogoncalves89 should this be changed to an anchor tag?

2022-02-22 00:01 UTC, ricardogoncalves89 requested changes
Run `npm run test` and check coverage pls

2022-02-22 16:48 UTC, djcouto approved these changes
LGTM 👍

2022-02-22 17:14 UTC, ricardogoncalves89 approved these changes

2022-02-22 17:18 UTC, merged