feat: add dropdown tree component [KMAPS-423]
kelvininc/ui-components pull request #151
Opened 2022-09-14 10:58 UTC by nelsonmestevao

2022-09-15 08:44 UTC, djcouto requested changes
I only left a few comments.

Please add a screenshot to give some context on what you achieved.

Nicely done 👍

2022-09-15 08:44 UTC, djcouto commented on packages/ui-components/src/components/tree-item/tree-item.base.scss
> +	 * @prop --vertical-lines-height: Line height of children's connectors.
I think it's missing the documentation for the other added CSS props. Not sure if it was intended.

2022-09-15 08:44 UTC, djcouto commented on packages/ui-components/src/components/tree/tree.base.scss
> +     * @prop --tree-node-width: Tree Node height.
Align this please 🙏

2022-09-15 08:44 UTC, djcouto commented on packages/ui-components/src/components/tree/tree.base.scss
> +     * @prop --tree-children-offset: Offset of the child nodes in px.
Missing the `--tree-children-padding-left` documentation

2022-09-15 08:44 UTC, djcouto commented on packages/ui-components/src/components/tree/tree.base.scss
> +	div {
give this div a meaningful class name and use it here

2022-09-15 14:59 UTC, djcouto approved these changes

2022-09-16 10:39 UTC, ricardogoncalves89 requested changes
Please have a look why your changes break the `kv-tree`
![image](https://user-images.githubusercontent.com/6940723/190621033-2d17c0b0-0e47-4098-9888-8952731f22fb.png)

2022-09-16 11:15 UTC, nelsonmestevao commented
@ricardogoncalves89 it is fixed now :pray:

2022-09-16 12:07 UTC, GoncaloCamaz approved these changes
Good job! 👍

2022-09-20 13:28 UTC, pedrorebelocosta requested changes

2022-09-20 13:28 UTC, pedrorebelocosta commented on packages/ui-components/src/components/tree-dropdown/tree-dropdown.tsx
> +		console.log(this.nodes);
remove console log

2022-09-21 14:42 UTC, ricardogoncalves89 approved these changes
🚀

2022-09-21 18:05 UTC, pedrorebelocosta approved these changes

2022-09-21 18:07 UTC, merged