feat(range): adding customization properties for range component
kelvininc/ui-components pull request #164
Opened 2022-09-27 16:54 UTC by TheSnakeRekt

2022-09-28 09:54 UTC, pedrorebelocosta approved these changes

2022-09-28 09:57 UTC, pedrorebelocosta commented on packages/ui-components/src/components/range/range.base.scss
>  	 * @prop --slider-background-filled: color of the slider when its full
rename this prop to `range` to keep consistency with the others ;)

2022-09-28 09:59 UTC, pedrorebelocosta requested changes

2022-09-28 09:59 UTC, pedrorebelocosta commented on packages/ui-components/src/components/range/range.base.scss
>  	 * @prop --slider-background-empty: color of the slider when its empty
same for this one ;)

2022-09-28 09:59 UTC, pedrorebelocosta commented on packages/ui-components/src/components/range/range.base.scss
>  	 * @prop --slider-background-filled: color of the slider when its full
rename this prop's prefix to `range-` to keep consistency with the others ;)

2022-09-28 10:05 UTC, djcouto requested changes
Besides what @pedrorebelocosta pointed out, just one more comment.

After that for me, you're good to go 👍

2022-09-28 10:05 UTC, djcouto commented on packages/ui-components/src/components/range/range.types.ts
> +	/** (optional) Show value label */
Hide value label? 😄 
Otherwise, change the prop name to `showLabel`

2022-09-28 10:08 UTC, djcouto approved these changes

2022-09-28 10:24 UTC, GoncaloCamaz commented on packages/ui-components/src/components/range/range.tsx
>  		const valueOffset = getValueOffset(percentage, inputValue);
I believe this valueOffset is only used inside the !this.hideLabel if. If so, maybe would be better to move this calculation inside the if

2022-09-28 11:31 UTC, GoncaloCamaz approved these changes

2022-09-28 11:56 UTC, ricardogoncalves89 requested changes
See my comment and the commit should have the break reference because you rename some css variables and it can cause some issues in applications that already use theses variables

2022-09-28 11:56 UTC, ricardogoncalves89 commented on packages/ui-components/src/components/range/range.base.scss
> +	 * @prop --range-selector-width: Width of the range thumb
`--range-selector-width` and `--range-selector-height` can be merged into one like `--range-selector-radius`

2022-09-29 13:46 UTC, ricardogoncalves89 approved these changes

2022-09-29 14:07 UTC, pedrorebelocosta approved these changes

2022-09-29 14:14 UTC, pedrorebelocosta commented
Before merging, make sure your commit message is correct as there is a space between the commit type and description:

current:
`feat(range) !: adding customization properties for range component`

when it should be: 
`feat(range)!: adding customization properties for range component`

2022-09-30 16:21 UTC, miguelpinto98 commented
@TheSnakeRekt Please fix the commit message and rebase.

2022-10-03 09:34 UTC, merged