feat(tooltip): add delay before show text [KMAPS-523]
kelvininc/ui-components pull request #171
Opened 2022-10-01 14:47 UTC by nelsonmestevao

2022-10-01 18:48 UTC, djcouto requested changes
Nice, just a few comments 💪

2022-10-01 18:48 UTC, djcouto commented on packages/react-ui-components/src/stories/Components/TreeDropdown.stories.tsx
> +			tooltipDelay={1000}
Please move this to a config file. Also this should be a configurable prop.

2022-10-01 18:48 UTC, djcouto commented on packages/react-ui-components/src/stories/Components/TreeDropdown.stories.tsx
> +			showTooltip
This should also be a configurable prop.

2022-10-01 18:50 UTC, djcouto commented
Sorry, my comments didn't make much sense 😅

2022-10-01 18:50 UTC, djcouto approved these changes

2022-10-03 10:42 UTC, miguelpinto98 approved these changes
👍  Good preventing the previous behaviour, and nice improvement for we want now.

2022-10-03 11:29 UTC, merged