feat(tooltip): add fade in/out animation to tooltip
kelvininc/ui-components pull request #197
Opened 2023-01-03 15:03 UTC by laraujo7

2023-01-03 15:19 UTC, miguelpinto98 requested changes
👌 Almost done, only check a small detail.

2023-01-03 15:19 UTC, miguelpinto98 commented on packages/ui-components/src/components/tooltip/readme.md
> -## CSS Custom Properties
check this documentation removal. It seems this property continues to exist in our scss.

2023-01-03 16:19 UTC, ricardogoncalves89 approved these changes

2023-01-03 16:55 UTC, GoncaloCamaz approved these changes

2023-01-04 10:39 UTC, djcouto approved these changes

2023-01-04 12:02 UTC, miguelpinto98 approved these changes

2023-01-04 12:32 UTC, merged