feat(icon): add forbidden circle
kelvininc/ui-components pull request #244
Opened 2023-02-27 12:52 UTC by feliciofilipe

2023-02-27 13:07 UTC, djcouto approved these changes
🚀

2023-02-27 13:09 UTC, miguelpinto98 approved these changes

2023-02-27 14:17 UTC, ricardogoncalves89 requested changes
All icons on our new design system should have an viewport 24x24.

2023-02-27 14:29 UTC, ricardogoncalves89 commented
Please add a preview to the description.

2023-02-28 10:24 UTC, GoncaloCamaz approved these changes

2023-02-28 11:59 UTC, pedrorebelocosta approved these changes

2023-02-28 18:19 UTC, laraujo7 approved these changes

2023-03-03 12:20 UTC, ricardogoncalves89 approved these changes

2023-03-03 12:22 UTC, merged