[WIP] feat(button): update design
kelvininc/ui-components pull request #249
Opened 2023-03-02 13:15 UTC by feliciofilipe

Adds the new design to the buttons according to the latest figma design spec.

The previous tertiary button is now the new secondary button.

The previous secondary button was removed.

The ghost button was added according to the design spec.

**WIP: Waiting for the confirmation on how components that rely on the buttons will update**

2023-03-14 10:12 UTC, djcouto requested changes
I think it's missing the alerts' button colours fix, right?

2023-03-14 10:14 UTC, feliciofilipe commented
@djcouto I'll look into it :nerd_face:

2023-03-14 12:08 UTC, djcouto approved these changes

2023-03-16 17:57 UTC, pedrorebelocosta approved these changes

2023-03-16 18:07 UTC, merged