feat(kv-tag-letter): migrate tag letter component
kelvininc/ui-components pull request #27
Opened 2022-02-24 17:30 UTC by ricardoarasilva

<img width="1584" alt="Captura de Tela 2022-02-24 às 14 29 39" src="https://user-images.githubusercontent.com/12516125/155576424-d885a3e8-06bc-4513-a18e-e15c96b49123.png">

2022-02-24 20:43 UTC, joshbode commented
Hey guys - do I need to be tagged on these PRs or am I being added accidentally? Looks like @ernananguiano and @andregomesk may be being added by default, too.

2022-02-24 20:49 UTC, paulosoaresvieira commented
> Hey guys - do I need to be tagged on these PRs or am I being added accidentally? Looks like @ernananguiano and @andregomesk may be being added by default, too.
it was a miss understanding you guys don't need to review this

2022-03-04 11:05 UTC, ricardogoncalves89 approved these changes
👌 fix only the typo and rebase with dev

2022-03-04 15:06 UTC, pedrorebelocosta requested changes

2022-03-04 15:06 UTC, pedrorebelocosta commented on packages/ui-components/src/components/tag-letter/usage/angular.md
> +<kv-tag-letter label="Tag Letter" tag-letter="T" />
in angular you can actually refer to the tagLetter property instead of the tag-letter attribute ;)

2022-03-04 15:06 UTC, pedrorebelocosta commented on packages/ui-components/src/components/tag-letter/usage/react.md
> +	<KvTagLetter label="Tag Letter" tag-letter="T" />
same as the comment for angular ;)

2022-03-04 15:06 UTC, pedrorebelocosta commented on packages/ui-components/src/components/tag-letter/tag-letter.tsx
> +	/** (optional) Tag letter's color */
One or two of the properties must be required no? Please double check this ;)

2022-03-07 19:01 UTC, pedrorebelocosta requested changes

2022-03-07 19:01 UTC, pedrorebelocosta commented on packages/ui-components/src/components/tag-letter/tag-letter.tsx
> +	/** (required) Tag letter's color */
make it explicitly required by adding a '!' after the variable name, i.e: `@Prop({ reflect: true }) color!: string;`

2022-03-07 19:02 UTC, pedrorebelocosta commented on packages/ui-components/src/components/tag-letter/tag-letter.tsx
> +	/** (required) Tag letter's color */
same for any other required properties

2022-03-07 19:27 UTC, pedrorebelocosta approved these changes

2022-03-07 20:59 UTC, merged