fix(tooltip): add tooltip floating content in body context
kelvininc/ui-components pull request #298
Opened 2023-05-25 16:06 UTC by ricardogoncalves89

2023-05-30 14:59 UTC, djcouto approved these changes
👏 🚀

2023-05-30 14:59 UTC, djcouto commented on packages/ui-components/src/utils/types/components.ts
> +export interface ICustomCss {
👌

2023-05-31 13:08 UTC, pedrorebelocosta approved these changes

2023-06-01 11:10 UTC, miguelpinto98 commented on packages/react-ui-components/src/stories/Components/Tooltip/Tooltip.stories.tsx
> +		<KvActionButtonText text={'Hover me!'} type={EActionButtonType.Primary} />
text="Hover me!"

2023-06-01 15:06 UTC, miguelpinto98 requested changes, later dismissed
well done! 👍 
I only left some comments to understand some points, after that we can continue.

2023-06-01 15:06 UTC, miguelpinto98 commented on packages/ui-components/src/components/portal/portal.tsx
> +				return unionWith(srcValue, objValue, (a, b) => a.name === b.name);
re-use this common code, please

2023-06-01 17:50 UTC, miguelpinto98 reviewed
since I will on vacation I will remove my requests

2023-06-13 14:12 UTC, miguelpinto98 approved these changes
👍

2023-06-13 14:23 UTC, merged