fix(icons): replace entity-asset and entity-area icons
kelvininc/ui-components pull request #299
Opened 2023-06-02 11:24 UTC by GoncaloCamaz

![Screenshot 2023-06-02 at 12 20 16](https://github.com/kelvininc/ui-components/assets/37366547/e20db809-6577-4947-983e-cc762278f5d1)

2023-06-02 11:31 UTC, djcouto requested changes
The previous `kv-entity-asset` icon was correct, according to our DS.

What we need is to add a new `kv-asset`.

2023-06-02 11:34 UTC, GoncaloCamaz commented
> 

That was not the information I had on the ticket. Will need to check.

2023-06-02 15:54 UTC, djcouto approved these changes

2023-06-07 15:54 UTC, pedrorebelocosta approved these changes

2023-06-12 16:25 UTC, miguelpinto98 approved these changes

2023-06-12 16:42 UTC, merged