feat(icons): add new schedule send icon
kelvininc/ui-components pull request #435
Opened 2024-04-16 08:50 UTC by GoncaloCamaz

2024-04-16 09:18 UTC, djcouto requested changes

2024-04-16 09:18 UTC, djcouto commented on packages/ui-components/src/assets/svg-symbols.svg
> +	<symbol id="kv-schedule-send" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
Let's use the 24x24 version of this icon please 🙏

2024-04-16 15:24 UTC, djcouto approved these changes

2024-04-17 13:08 UTC, miguelpinto98 approved these changes

2024-04-17 13:09 UTC, merged