fix(select): add ellipsis to items counter
kelvininc/ui-components pull request #477
Opened 2024-09-24 09:08 UTC by GoncaloCamaz

2024-09-24 09:22 UTC, djcouto requested changes

2024-09-24 09:22 UTC, djcouto commented on packages/ui-components/src/components/select-multi-options/select-multi-options.tsx
> +						<kv-tooltip text={selectedItemsCountText}>
We should use the tooltip truncate prop here instead.

2024-09-24 10:34 UTC, djcouto approved these changes

2024-09-24 10:34 UTC, djcouto commented on packages/ui-components/src/components/select-multi-options/select-multi-options.scss
> +	@include ellipsis();
I don't think we still need this after your latest changes.

2024-09-25 21:38 UTC, miguelpinto98 approved these changes
Approved, but with one question. 
Does it really make sense to truncate/hide the selected items?

2024-09-26 10:50 UTC, GoncaloCamaz commented
> Approved, but with one question. Does it really make sense to truncate/hide the selected items?

The dropdown width is still configured from the outside in case we want to prevent this problem.

2024-09-26 16:02 UTC, merged