fix(illustration): change something-went-wrong colors
kelvininc/ui-components pull request #59
Opened 2022-03-17 12:25 UTC by djcouto

<img width="467" alt="Screenshot 2022-03-17 at 12 25 19" src="https://user-images.githubusercontent.com/17494742/158807967-ecaa1c96-002c-4c6e-9ba0-702e4039a0b7.png">

2022-03-17 12:45 UTC, miguelpinto98 requested changes

2022-03-17 12:45 UTC, miguelpinto98 commented on packages/ui-components/src/assets/svg-symbols.svg
>  	<symbol id="kv-es-section-somethingwentwrong"
this illustration works with light theme? Probably some colors needs to be defined in a variable.

2022-03-18 10:30 UTC, ricardoarasilva approved these changes

2022-03-18 13:12 UTC, miguelpinto98 approved these changes

2022-03-22 17:13 UTC, merged