feat(tree-item): add tree item component
kelvininc/ui-components pull request #86
Opened 2022-05-10 15:58 UTC by ricardogoncalves89

**NIGHT MODE:**
>![image](https://user-images.githubusercontent.com/6940723/167670879-de2a8d7f-9831-451e-b630-ca24357ce5d6.png)![image](https://user-images.githubusercontent.com/6940723/167671038-0c09feb2-a4d4-40a4-957d-d32925fd03bd.png)

**LIGHT MODE:**
>![image](https://user-images.githubusercontent.com/6940723/167671432-9875320c-6eea-474f-bb6b-fb6c0da46dd0.png)![image](https://user-images.githubusercontent.com/6940723/167671491-ac390ceb-b963-4e1f-b74e-d057ff90adfb.png)

2022-05-12 17:26 UTC, GoncaloCamaz approved these changes

2022-05-13 14:44 UTC, pedrorebelocosta approved these changes
just a single consideration :P

2022-05-13 14:44 UTC, pedrorebelocosta commented on packages/react-ui-components/src/stories/Components/TreeItem.stories.tsx
> +	title: 'Navigation/Tree/Tree Item',
Wouldn't this component be a better fit in the Data Display category? I understand the consideration regarding Navigation, but I'm unsure if it's the best category for it.

2022-05-13 17:38 UTC, miguelpinto98 requested changes
Seems very good 💪  
Only a few small changes to go

2022-05-13 17:38 UTC, miguelpinto98 commented on packages/react-ui-components/src/stories/Components/TreeItem.stories.tsx
> +const handleToggleExpand = (e: any) => console.log('onToggleExpand', e);
We should move the actions callbacks to `argTypes` with this options:

```
onItemClick: {
		action: 'clicked'
},
onToggleExpand: {
		action: 'clicked'
}
```

After that we can remove from the template the bind for this function.

2022-05-13 17:38 UTC, miguelpinto98 commented on packages/react-ui-components/src/stories/Components/TreeItem.stories.tsx
> +const ChildrenTreeTemplate: ComponentStory<typeof KvTreeItem> = args => {
`args` isn't used and the `counter` receive a number by definition, this are generating some warnings

2022-05-13 18:04 UTC, miguelpinto98 commented on packages/ui-components/src/components/tree-item/tree-item.types.ts
> +export enum ETreeItemStates {
Use singular for enums `ETreeItemState`

2022-05-16 11:19 UTC, miguelpinto98 approved these changes
👊

2022-05-16 11:26 UTC, merged